spring:
  profiles:
    active: local

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

slack:
  incoming-hook-url: ${SLACK_INCOMING_HOOK_URL}

cloud:
  aws:
    s3:
      bucket: rednotice-sample
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: eu-north-1
      auto: false
    stack:
      auto: false


