spring:
  datasource:
    url: jdbc:mysql://rednotice-db.chc6aqwsg4ny.ap-northeast-2.rds.amazonaws.com:3306/rednotice

    username: admin
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

---
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
